<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_coding"
 *
 * Auto generated by Extension Builder 2015-03-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Coding',
	'description' => 'An Extension to collect your coding examples',
	'category' => 'plugin',
	'author' => 'Tobias Maxham',
	'author_email' => 'tobias.maxham@tricept.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);